# Basic envctl configuration example
# This shows a minimal configuration with the new cluster system

globalSettings:
  defaultContainerRuntime: "docker"

# Define your clusters
clusters:
  # Management cluster for monitoring infrastructure
  - name: "mc-prod"
    context: "teleport.giantswarm.io-production"
    role: "observability"
    displayName: "Production MC"
    icon: "🏢"
  
  # Workload cluster where your applications run
  - name: "wc-prod-apps"
    context: "teleport.giantswarm.io-production-apps"
    role: "target"
    displayName: "Production Apps"
    icon: "🚀"

# Set which cluster is active for each role
activeClusters:
  observability: "mc-prod"
  target: "wc-prod-apps"

# Port forwards define which services to expose locally
portForwards:
  - name: "mc-prometheus"
    enabledByDefault: true
    icon: "📊"
    category: "Monitoring"
    clusterRole: "observability"  # Uses the active observability cluster
    namespace: "mimir"
    targetType: "service"
    targetName: "mimir-query-frontend"
    localPort: "8080"
    remotePort: "8080"
  
  - name: "mc-grafana"
    enabledByDefault: true
    icon: "📈"
    category: "Monitoring"
    clusterRole: "observability"
    namespace: "mimir"
    targetType: "service"
    targetName: "grafana"
    localPort: "3000"
    remotePort: "3000"
  
  # Additional app-specific port forward
  - name: "app-api"
    enabledByDefault: false
    icon: "🔌"
    category: "Applications"
    clusterRole: "target"  # Uses the active target cluster
    namespace: "production"
    targetType: "service"
    targetName: "api-gateway"
    localPort: "8000"
    remotePort: "80"

# MCP servers provide AI assistants with access to your clusters
mcpServers:
  # Kubernetes MCP server for cluster operations
  - name: "kubernetes"
    type: "localCommand"
    enabledByDefault: true
    icon: "☸️"
    category: "Core"
    command: ["mcp-server-kubernetes"]
    requiresClusterRole: "target"  # Connects to the active target cluster
  
  # Prometheus MCP server for metrics queries
  - name: "prometheus"
    type: "localCommand"
    enabledByDefault: true
    icon: "📊"
    category: "Monitoring"
    command: ["mcp-server-prometheus"]
    env:
      PROMETHEUS_URL: "http://localhost:8080"
      ORG_ID: "1"  # For multi-tenant Prometheus
    requiresPortForwards:
      - "mc-prometheus"

  # Grafana MCP server for dashboard access
  - name: "grafana"
    type: "localCommand"
    enabledByDefault: true
    icon: "📈"
    category: "Monitoring"
    command: ["mcp-server-grafana"]
    requiresPortForwards: ["mc-grafana"]
    env:
      GRAFANA_URL: "http://localhost:3000" 