name: "serviceclass-with-preconfigured-dependencies"
category: "behavioral"
concept: "serviceclass"
description: "Test ServiceClass with pre-configured dependencies and workflows"
tags: ["serviceclass", "dependencies", "workflow", "mock"]
timeout: "7m"

# Pre-configuration for this test scenario
pre_configuration:
  mcp_servers:
    - name: "database-mock"
      config:
        tools:
          - name: "database_create"
            description: "Create a database instance"
            input_schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  required: true
                engine:
                  type: "string"
                  default: "postgresql"
                version:
                  type: "string"
                  default: "14"
                storage_size:
                  type: "string"
                  default: "20Gi"
            responses:
              - response:
                  status: "created"
                  database_id: "db-{{ .name }}-{{ .engine }}"
                  name: "{{ .name }}"
                  engine: "{{ .engine }}"
                  version: "{{ .version }}"
                  storage_size: "{{ .storage_size }}"
                  state: "available"
                  endpoint: "{{ .name }}.db.example.com:5432"
                delay: "8s"

          - name: "database_delete"
            description: "Delete a database instance"
            input_schema:
              type: "object"
              properties:
                database_id:
                  type: "string"
                  required: true
            responses:
              - response:
                  status: "deleted"
                  database_id: "{{ .database_id }}"
                delay: "5s"

    - name: "loadbalancer-mock"
      config:
        tools:
          - name: "loadbalancer_create"
            description: "Create a load balancer"
            input_schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  required: true
                type:
                  type: "string"
                  default: "application"
                scheme:
                  type: "string"
                  default: "internet-facing"
            responses:
              - response:
                  status: "created"
                  loadbalancer_id: "lb-{{ .name }}-{{ .type }}"
                  name: "{{ .name }}"
                  type: "{{ .type }}"
                  scheme: "{{ .scheme }}"
                  state: "active"
                  dns_name: "{{ .name }}-lb.example.com"
                delay: "4s"

          - name: "loadbalancer_delete"
            description: "Delete a load balancer"
            input_schema:
              type: "object"
              properties:
                loadbalancer_id:
                  type: "string"
                  required: true
            responses:
              - response:
                  status: "deleted"
                  loadbalancer_id: "{{ .loadbalancer_id }}"
                delay: "3s"

  # Configure workflows that will be available
  workflows:
    - name: "deploy-with-monitoring"
      config:
        name: "deploy-with-monitoring"
        description: "Deploy service with monitoring setup"
        input_schema:
          service_name:
            type: "string"
            required: true
          namespace:
            type: "string"
            default: "default"
        steps:
          - id: "deploy-service"
            tool: "x_kubernetes_apply"
            args:
              yaml: "{{ .service_yaml }}"
          - id: "setup-monitoring"
            tool: "x_prometheus_add_target"
            args:
              target: "{{ .service_name }}.{{ .namespace }}.svc.cluster.local:8080"

  # Configure a service class that uses the above components
  service_classes:
    - name: "monitored-web-service"
      config:
        name: "monitored-web-service"
        type: "stateful"
        version: "1.0.0"
        description: "Web service with monitoring integration"
        parameters:
          app_name:
            type: "string"
            required: true
          image:
            type: "string"
            required: true
          port:
            type: "integer"
            default: 8080
          replicas:
            type: "integer"
            default: 2
        serviceConfig:
          lifecycleTools:
            start:
              tool: "x_kubernetes_apply"
              arguments:
                yaml: "{{ .template }}"
            stop:
              tool: "x_kubernetes_delete"
              arguments:
                name: "{{ .app_name }}"
                namespace: "{{ .namespace | default \"default\" }}"
        template: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ .parameters.app_name }}"
            namespace: "{{ .parameters.namespace | default "default" }}"
          spec:
            replicas: {{ .parameters.replicas }}
            selector:
              matchLabels:
                app: "{{ .parameters.app_name }}"
            template:
              metadata:
                labels:
                  app: "{{ .parameters.app_name }}"
              spec:
                containers:
                - name: app
                  image: "{{ .parameters.image }}"
                  ports:
                  - containerPort: {{ .parameters.port }}

  # Configure main envctl settings
  main_config:
    config:
      logging:
        level: "debug"
      server:
        host: "localhost"
        timeout: "30s"

steps:
  - id: verify-preconfig-loaded
    description: "Verify that pre-configured components are available"
    tool: "core_mcpserver_list"
    args: {}
    expected:
      success: true
      contains: ["database-mock", "loadbalancer-mock"]
    timeout: "30s"

  - id: check-workflow-available
    description: "Verify the pre-configured workflow is available"
    tool: "core_workflow_list"
    args: {}
    expected:
      success: true
      contains: ["deploy-with-monitoring"]
    timeout: "30s"

  - id: check-serviceclass-available
    description: "Verify the pre-configured ServiceClass is available"
    tool: "core_serviceclass_list"
    args: {}
    expected:
      success: true
      contains: ["monitored-web-service"]
    timeout: "30s"

  - id: verify-serviceclass-ready
    description: "Check if the ServiceClass is ready for instantiation"
    tool: "core_serviceclass_available"
    args:
      name: "monitored-web-service"
    expected:
      success: true
      json_path:
        available: true
        missing_tools: []
    timeout: "30s"

  - id: create-service-instance
    description: "Create a service instance from the pre-configured ServiceClass"
    tool: "core_service_create"
    args:
      serviceClassName: "monitored-web-service"
      label: "test-web-app"
      parameters:
        app_name: "test-web-app"
        image: "nginx:latest"
        port: 80
        replicas: 1
    expected:
      success: true
      contains: ["created successfully", "test-web-app"]
    timeout: "2m"

  - id: verify-service-created
    description: "Verify the service instance was created"
    tool: "core_service_list"
    args: {}
    expected:
      success: true
      contains: ["test-web-app", "Running"]
    timeout: "30s"

  - id: get-service-status
    description: "Get detailed status of the created service"
    tool: "core_service_status"
    args:
      label: "test-web-app"
    expected:
      success: true
      contains: ["Running", "monitored-web-service"]
    timeout: "30s"